### ISSUE TITLE
macos arm64 support

### ISSUE THREAD

**Issue by chulkilee** [garden-io/homebrew-garden#70]
~~0.13.2~~ 0.13.12 comes with macos arm64 binary - https://github.com/garden-io/garden/releases

**Comment by vvagaytsev** [comment]
@chulkilee thanks for reporting this! Did you mean `0.13.2`?
Does `garden self-update 0.13.2` work as a workaround?

@TimBeyer can you take a look, please?

**Comment by chulkilee** [comment]
```
brew reinstall garden-io/garden/garden-cli
```

This installs amd64 not arm64 for m1 machine.

```
https://download.garden.io/core/0.13.12/garden-0.13.12-macos-amd64.tar.gz
```

which gives `bad CPU type in executable: garden` error for terminal not running Rosetta.

Also I don't think you can self-update it from amd64 to arm64 as Rosetta terminal (running amd64 exectuables) would return amd64 for uname.

Please update the brew config to handle both amd64 and arm64.

**Comment by stefreak** [comment]
@chulkilee thank you for reporting this, we now updated the Homebrew tap to support ARM64 with the PR #77

Please run `brew update && brew upgrade garden-cli`
